[source]
name = "uniform"
nphotons = 1000000
direction = [1.0, 0.0, 0.0]
point1 = [-7.5, -1.0, -1.0]
point2 = [0.0, 2.0, 0.0]
point3 = [0.0, 0.0, 2.0]

[grid]
nxg = 200
nyg = 200
nzg = 200
xmax = 7.50
ymax = 7.50
zmax = 7.50

[[detectors]]
type="circle"
position=[-7.5, 0.0, 0.0]
direction=[-1.0, 0.0, 0.0]
layer=4
radius1=100.0
nbins=500
maxval = 5000.0
trackHistory=false

[geometry]
geom_name = "test_egg"

[output]
fluence = "egg_rus.nrrd"
render = "egg_geom.nrrd"
render_geom = false
overwrite = true

[simulation]
iseed = 123456789
tev = false