[source]
name = "point"
nphotons = 100000
position = [0.0, 0.0, 0.0]
spectrum_type = "constant"
wavelength = 500.0

[grid]
nxg = 200
nyg = 200
nzg = 200
xmax = 1.0
ymax = 1.0
zmax = 1.0

[[detectors]]
type="circle"
position=[-1.0, 0.0, 0.0]
direction=[-1.0, 0.0, 0.0]
layer=4
radius1=0.5
nbins=10
maxval = 5000.0
trackHistory=false

[[detectors]]
type="annulus"
position=[-1.0, 0.0, 0.0]
direction=[-1.0, 0.0, 0.0]
layer=3
radius1=0.5
radius2=1.0
nbins=10
maxval = 5000.0
trackHistory=false

[[detectors]]
type="camera"
layer=2
p1=[-1.0, -1.0, -1.0]
p2=[0.0, 2.0, 0.0]
p3=[0.0, 0.0, 2.0]
nbins=10
maxval = 5000.0
trackHistory=false


[geometry]
geom_name = "scat_test"
tau = 10.0

[output]
fluence = "fluence.nrrd"
render = "geom_render.nrrd"
render_geom = false
overwrite = true

[simulation]
iseed = 123456789
absorb=true